---

- hosts: all
  become: true
  gather_facts: false
  become_user: root
  pre_tasks:
  - debug:
      msg: "{{ ansible_ssh_host }}"

  tasks:
    - name: Create profile directory
      file: 
        path: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}"
        state: directory
    - name: Get inspec tests profile
      get_url:
        url: "{{ inspec_tests_url }}"
        dest: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}/inspec_tests.zip"
        mode: '0660'
        validate_certs: no
    - name: Extract inspec tests profile
      unarchive:
        src: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}/inspec_tests.zip"
        dest: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}/inspec_tests"
        remote_src: yes
      changed_when: False
    - name: Execute inspec tests
      shell: |
        cd {{ inspec_exec_directory }
        {{ inspec_exec_cmd }} --config config.json {{ inspec_profiles_directory }}/inspec_tests/inspec-tests-main
      register: inspec_test_output
    - name: Show inspect test output
      debug:
        msg: |
          inspec test output:
          {{ inspec_test_output | to_nice_json }}

