---

- hosts: all
  become: true
  gather_facts: false
  become_user: root
  pre_tasks:
  - debug:
      msg: "{{ ansible_ssh_host }}"

  tasks:
    - name: Get {{ inspec-exec-profiles.name }} profile
      get_url:
        url: "{{ inspec-exec-profiles.url }}"
        dest: "~/inspec/profile/{{ inspec-exec-profiles.url }}.zip"
        mode: '0660'
        validate_certs: no
