---

- hosts: all
  become: true
  gather_facts: false
  become_user: root
  pre_tasks:
  - debug:
      msg: "{{ ansible_ssh_host }}"

  tasks:
    - name: Create profile directory
      file: 
        path: "~/inspec/profile"
        state: directory
    - name: Get inspec tests profile
      get_url:
        url: "https://github.com/d700qt/inspec-tests/archive/refs/heads/main.zip"
        dest: "~/inspec/profile/inspec_tests.zip"
        mode: '0660'
        validate_certs: no
