---

- hosts: all
  become: true
  gather_facts: false
  become_user: root
  pre_tasks:
  - debug:
      msg: "{{ ansible_ssh_host }}"

  tasks:
    - name: Create profile directory
      file: 
        path: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}"
        state: directory

    - name: Get inspec tests profile
      get_url:
        url: "{{ inspec_tests_url }}"
        dest: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}/inspec_tests.zip"
        mode: '0660'
        validate_certs: no
        force: yes

    - name: Extract inspec tests profile
      unarchive:
        src: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}/inspec_tests.zip"
        dest: "{{ inspec_exec_directory }}/{{ inspec_profiles_directory }}"
        remote_src: yes
      changed_when: False

    - name: Execute inspec tests
      shell: |
        cd {{ inspec_exec_directory }}/{{ inspec_profiles_directory }}/inspec-tests-main
        {{ inspec_exec_cmd }} --config {{ inspec_exec_directory }}/config.json --waiver-file waivers.yml --waiver-file waivers2.yml --log-level error --no-distinct-exit .
      failed_when: inspec_test_output.rc != 100 and inspec_test_output.rc != 101 and inspec_test_output.rc != 0
      register: inspec_test_output

    - name: Show inspect test output
      debug:
        msg: |
          inspec test output:
          {{ inspec_test_output }}
          {{ inspec_test_output.rc }}

