---

- hosts: all
  become: true
  gather_facts: false
  become_user: root
  pre_tasks:
  - debug:
      msg: "{{ ansible_ssh_host }}"

# - hosts: all
#   become: true
#   gather_facts: false
#   roles:
#     - inspec-exec