---

- hosts: all
  become: true
  gather_facts: false
  become_user: root
  pre_tasks:
  - debug:
      msg: "{{ ansible_ssh_host }}"

  tasks:
    - name: Create profile directory
      file: 
        path: "~/inspec/profile/inspec_tests"
        state: directory
    - name: Get inspec tests profile
      get_url:
        url: "https://github.com/d700qt/inspec-tests/archive/refs/heads/main.zip"
        dest: "~/inspec/profile/inspec_tests.zip"
        mode: '0660'
        validate_certs: no
    - name: Extract inspec tests profile
      unarchive:
        src: "~/inspec/profile/inspec_tests.zip"
        dest: "~/inspec/profile/inspec_tests"
        remote_src: yes
      changed_when: False
    - name: Execute inspec tests
      shell: |
        cd ~/inspec
        inspec exec --insecure --config config.json profile/inspec_tests/inspec-tests-main
      register: inspec_test_output
    - name: Show inspect test output
      debug:
        output: {{ inspec_test_output }}

